image: golang:1.11-alpine

clone:
  depth: full

stepdefinitions:
  - buildtest: &buildtest
      name: Build and test
      script:
        - apk add --update --no-cache gcc musl-dev git tar
        - PACKAGE_PATH="${GOPATH}/src/bitbucket.org/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}"
        - mkdir -pv "${PACKAGE_PATH}"
        - tar -cO --exclude-vcs --exclude=bitbucket-pipelines.yml . | tar -xv -C "${PACKAGE_PATH}"
        - cd "${PACKAGE_PATH}"
        - go get -v
        - go build -v
        - go test -v
  - deploy: &deploy
      name: Deploy to Heroku
      script:
        - apk add --update --no-cache git
        - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD

pipelines:
  branches:
    default:
      - step: *buildtest
    master: 
      - step: *buildtest
      - step: *deploy
